### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by blessyperumal** [blessyperumal/sep-22-developers#1]
## To Do List

- [x] Create an issue
- [ ] Create a branch
- [ ] Edit files locally and push it
- [ ] Create a Pull req
- [ ] Edit files GitHub.com and pull it
- [ ] Merge a Pull req
- [ ] Merry Christmas? 

:christmas_tree: :santa: :+1:
